name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'extension :gear:'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Append Issue Body
        uses: julien-deramond/update-issue-body@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Verification Tasks

            description stuff goes here

            - [ ] Task 1

            - [ ] Task 2

            - [ ] Task 3
          edit-mode: append
          append-separator: newline