# This is a basic workflow that is manually triggered

name: Update Extensions Manifest

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run?"
        required: true
        type: boolean
        default: false  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 8 * * *'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  Update-Extensions-Manifest:  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    
    env:
      DRY_RUN: ${{ !!(inputs.dry-run) }}
      NEXUS_APIKEY: ${{ secrets.NEXUS_APIKEY }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Show Inputs
      run: echo "${{ toJSON(inputs) }}"

    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: "yarn"

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run
      run: yarn update-extensions-manifest

    - name: Git commit and push      
      if: ${{ env.DRY_RUN == 'false' }}
      env: 
        CI_COMMIT_AUTHOR: Vortex Backend
        CI_COMMIT_EMAIL: insomnious@users.noreply.github.com
        CI_COMMIT_MESSAGE: Update Extensions Manifest
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git pull
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
